name: Docker Build/Scan/Push

on:
  push:
    branches:
      - main

env:
  GITHUB_REF_NAME: "main"
  GITHUB_ACTOR: "brad.otlin@wiz.io"
  GITHUB_REPOSITORY: "https://github.com/bradotlin/github_demo/"
  GITHUB_SHA: "3af5929b750598e2b8c11550f11d71adbbe3e1c8"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  Build-Scan-Push:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      IMAGE_REPO: eyembrad/github
      IMAGE_TAG: latest
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      WIZ_POLICY: "otlin Default vulnerabilities policy"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the latest Docker image
        run: docker build -t ${IMAGE_REPO}:${IMAGE_TAG} -f ./Dockerfile .

      - name: Download Wiz CLI
        run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

      - name: Authenticate to Wiz
        run: sudo -E ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

      - name: Run Wiz CLI image scan
        id: scan
        run: |-
          sudo -E ./wizcli docker scan -i ${IMAGE_REPO}:${IMAGE_TAG} --policy "$WIZ_POLICY" --policy-hits-only \
          --driver mountWithLayers --dockerfile "./Dockerfile" --output wiz-output.json,sarif,true --tag github_action_run_id=${{ github.run_id }}
        continue-on-error: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push the latest Docker image
        run: docker push ${IMAGE_REPO}:${IMAGE_TAG}

      - name: Run Wiz CLI image tag
        run: sudo -E ./wizcli docker tag -i ${IMAGE_REPO}:${IMAGE_TAG}

      - name: SSH to VM to run container
        run: |
          # Set Docker CLI to use the remote host via SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.REMOTE_HOST }} "sudo pwd"
         # ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.REMOTE_HOST }} "sudo docker ps -a --format '{{.Names}}' | grep -w "gh-container" && sudo docker stop gh-container"# ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.REMOTE_HOST }} "sudo docker ps -a --format '{{.Names}}' | grep -w "gh-container" && sudo docker stop gh-container"
         # ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.REMOTE_HOST }} "sudo docker images -q eyembrad/github:latest | grep -q . && sudo docker rmi eyembrad/github:latest"
         # ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.REMOTE_HOST }} "sudo docker run -it --rm -d --name gh-container -p 8181:80 eyembrad/github:latest"
